# 1. Scalars & Vectors
* Scalars is a single number, denoted as x
* We can see scalars as constants/values that are use to scale a given vector

* Vector is an array of scalars, denoted by x
* * Thus a vector has n scalars x1, x2, x3 ... xn
* * Vectors can be seen as lists (from perspective of computer science student) and as arrows
in space (from perspective of physics student)
* * Note that the indexing here begins with 1, unlike python.

In [2]:
import numpy as np

In [2]:
# We will represent vector as a row vector, that is having multiple columns
x1 = np.array([4,5,6])
print(x1)
print(x1.shape)

[4 5 6]
(3,)


In [3]:
# We will represent vector as a column vector, that is having multiple rows
x = np.array([[4], [5], [8]])
print(x)
print(x.shape)

[[4]
 [5]
 [8]]
(3, 1)


In [4]:
# Can also represent x1 as column vetor by:
print(x1.reshape(3,1))

[[4]
 [5]
 [6]]


In [5]:
# There is a change in how we access elements using indexing in row and column vector

# In row vector we, it returns an element as there is only one row (as by shape it has only 1 dimension)
print(x1[0])

# In column vector it returns the whole first row (this is treated as 2 dimentional matrix)
print(x[0])

4
[4]


# 2. Matrices & Tensors
* Matrix is a 2D array of scalars, denoted by X(italics)
![alt text](pictures/Matrices.jpg "Matrix")
* * This matrix has 2(m) rows and 2(n) columns
* * Each individual element of this matrix is a scalar
* * if m = n, then matrix is known as Square matrix

* Tensor is an array with more than 2 axes, denoted by X
#![alt text](pictures/tensors1.jpg "Tensor1")
* * Think of Tensor as a generalization of an array with more than 2 axes
* * We can see tensors as more than one (m x n) matrices stacked in layers one beneath 
the other
![alt text](pictures/tensors2.jpg "Tensor2")
* * Are very useful in deep learning and neural networks

In [3]:
# Here X is a matrix
X = np.array([[4,5,7], [10,11,13], [56,80,90]]) # This is a 3x3 matrix
print(X.shape)
print(X)

(3, 3)
[[ 4  5  7]
 [10 11 13]
 [56 80 90]]


In [7]:
# Here T is a Tensor
T = np.array([[[4,5,7], [10,11,13]], [[56,80,90], [9,8,10]]])

print(T.shape)
print(T)

(2, 2, 3)
[[[ 4  5  7]
  [10 11 13]]

 [[56 80 90]
  [ 9  8 10]]]


In [8]:
# Here there are 3 layered 2x2 matrices
# matrix 1: 4 10
#           56 9

# matrix 2: 5 11
#           80 8

# matrix 3: 7 13
#           90 10

# they are all stacked together in three layers

# 3. Transpose
* For a 2D matrix transpose can be obtained by A(i,j) = A(j,i)
* Its like taking a mirror image along the diagonal
* For a vector transpose makes a column vector into a row. Thus a column vector can also be represented as X = [x1, x2, x3 ... xn]^T.

In [6]:
# Transpose of x:
print(X)
Xt = np.transpose(X)
print(Xt)

[[ 4  5  7]
 [10 11 13]
 [56 80 90]]
[[ 4 10 56]
 [ 5 11 80]
 [ 7 13 90]]


In [13]:
# transpose by manual method
y = x.reshape((-1,1))
print(y)
print(np.transpose(y))
print(np.transpose(y).shape)

[[4]
 [5]
 [8]]
[[4 5 8]]
(1, 3)


# 4. Broadcasting
* You can add a scalar to a vector, and numpy will add it to each element in the vector
* Similarly you can add a vector to a matrix, and numpy will add the vector to each column/row of the matrix accordingly
* **It is easier to perform these simple operations involving scalars to each element of list in numpy arrays as it treats everything as a vector/matrix and is very difficult using normal python list**

In [8]:
l1 = np.array([1,2,3,4])
l1 = l1 + 1 # Broadcasting operation
print(l1)

[2 3 4 5]


In [4]:
# Trying to perform the same operation on a normal python list
l2 = [1,2,3,4]
l2 = l2 + 1
print(l2)

# This returns an error as no mathematical operations are allowed directly on python lists as a whole

TypeError: can only concatenate list (not "int") to list

In [7]:
# Repeating the same but by forming a mathematical function
l2 = [1,2,3,4]
l2 = list(map(lambda x: x+1, l2))
print(l2)

# Now we can see that we can perform this operation in a much simpler way if using numpy arrays

[2, 3, 4, 5]


In [9]:
# We can perform broadcasting operations on  matrix too
l = np.array([[1,2,3,4], [5,6,7,8]])
print(l)
l = l**2
print(l)


[[1 2 3 4]
 [5 6 7 8]]
[[ 1  4  9 16]
 [25 36 49 64]]


In [11]:
np.sqrt(l, dtype='float64')

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])