# 1. Matrix Multiplication
* C= AB is only defined when the second dimension of A matches the first dimension of B
* Further, if A is of shape(m, n) and B is of shape (n, p), then C is of shape(m,p)
* C(ij) is computed by taking the dot product of i-th row of A with j-th column of B
* A more useful method to think of matrix multiplication is as linear combination of columns of A weighted by column entries of B
![alt text](pictures/matrix_multiplication_weighted.jpg "matrix multiplication")

In [1]:
import numpy as np

In [3]:
X = np.array([[4,5,7], [10, 11,13], [56,80,90]])
Y = np.array([[40,50,70], [100,110,130], [560,800,900]])


In [4]:
print(X.shape)
print(Y.shape)

print(X)
print(Y)

(3, 3)
(3, 3)
[[ 4  5  7]
 [10 11 13]
 [56 80 90]]
[[ 40  50  70]
 [100 110 130]
 [560 800 900]]


In [5]:
# To get the matrix multiplication result of the two arrays:
prod = np.dot(X,Y)
print(prod)

[[ 4580  6350  7230]
 [ 8780 12110 13830]
 [60640 83600 95320]]


# 2. Element Wise multiplication: Hadamard poduct
**Notice** How numpy uses * for this. Important to be careful, and not to confuse this with matrix multiplication

In [6]:
X = np.array([[4,5,7], [10, 11,13], [56,80,90]])
Y = np.eye(3)

print(X)
print(Y)

[[ 4  5  7]
 [10 11 13]
 [56 80 90]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
# Element wise multiplication:
print(X*Y)

#VS
# Matrix multiplication
print(np.dot(X,Y))

[[ 4.  0.  0.]
 [ 0. 11.  0.]
 [ 0.  0. 90.]]
[[ 4.  5.  7.]
 [10. 11. 13.]
 [56. 80. 90.]]


In [8]:
# Some more element wise operations
Y = Y*2
Y = Y+1

print(Y)

[[3. 1. 1.]
 [1. 3. 1.]
 [1. 1. 3.]]


In [9]:
Y = Y+5

In [10]:
print(Y)

[[8. 6. 6.]
 [6. 8. 6.]
 [6. 6. 8.]]


# 3. Norms
* Norms can be thought of as a proxy for size of a vector
![alt text](pictures/norm.jpg "norms")

In [3]:
X = np.array([-5,3,10])

In [5]:
# Finding norm of a vector using numpy
lp2 = np.linalg.norm(X) # By default it is treated as L2 norm and 'linalg' stands for linear algebra module
print(lp2)


11.575836902790225


In [6]:
# If we have to find norm of some other order like L1 or L3:
lp1 = np.linalg.norm(X, ord = 1) # L1 norm

lpinf = np.linalg.norm(X, ord = np.inf) # L(infinity) norm
# L(infinity) norm returns the absolute value of the greates value in that vector

print(lp2)
print(lpinf)

11.575836902790225
10.0


# 4. Determinants
More Operations on Matrices, [click here](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [3]:
A = np.array([[1,2],
              [3,4]])


np.linalg.det(A)

-2.0000000000000004

# 5. Inverse
In the following code we will implement two types of inverses,<br>
1. **Normal Inverse:** This can only be calculated when the determinant of a matrix is non-zero and is a square matrix.
2. **Moore-Penrose Pseudo Inverse:** This inverse can be calculated on non-zero and non-square matrices. If the matrix is invertible we get the same result as a normal inverse. For more information about this [click here](https://www.itl.nist.gov/div898/software/dataplot/refman2/auxillar/pseudinv.htm#:~:text=The%20Moore%2DPenrose%20pseudo%20inverse%20is%20a%20generalization%20of%20the,when%20A%20is%20not%20invertible.).

In [4]:
A = np.array([[1,2],
              [3,4]])

Ainv = np.linalg.inv(A) # Normal Inverse
print(Ainv)
       
pinv = np.linalg.pinv(A) # Pseudo Inverse
print(pinv)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [7]:
B = np.array([[6,3], # Matrix with determinant = 0
              [8,4]])
pinv = np.linalg.pinv(B)
print(inv)

[[0.048 0.064]
 [0.024 0.032]]


# 6. Solve a System of Equations
This can we used to solve a system of linear equations, [click here](https://numpy.org/doc/stable/reference/generated/numpy.linalg.solve.html#numpy.linalg.solve) to view the function.

In [8]:
a = np.array([[2,3], [3,1]])
b = np.array([8,5])

np.linalg.solve(a,b)

array([1., 2.])

In [2]:
A = np.array([[2, 4, 6],
              [4, 5, 6],
              [3, 1, -2]])
B = np.array([18, 24, 4])

print(np.linalg.solve(A,B))

[ 4. -2.  3.]
