# Working with Numpy - for mathematical operations

In [1]:
import numpy as np

### Creating arrays

In [2]:
# Using inbuilt numpy range function
a = np.arange(10) # can also give start, stop and step as parameters like normal range function
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(a+5)

[ 5  6  7  8  9 10 11 12 13 14]


In [46]:
# Using lists
a = np.array([1,2,3,4,5])

In [3]:
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
print(a.shape)
# Shape return a tuple that has dimentions of your array
# Can have n dimentions

(5,)


In [47]:
b = np.array([[1], [2], [3], [4], [5]])
print(b)
print(b.shape)
# This is a 2D array where as 'a' was a linear array

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [7]:
print(b[0])
print(b[0][0])

[1]
1


In [9]:
c = np.array([[1,2,3], [4,5,6]])
print(c)
print(c.shape)
print(c[1][1])

[[1 2 3]
 [4 5 6]]
(2, 3)
5


In [11]:
# Some usefull inbuilt functions for creating arrays
a = np.zeros((3,3)) # Have to specify (rows, cols) in a tuple ALWAYS.
print(a)

b = np.ones((2,3))
print(b)

# Array of some constants
c = np.full((3,2), 5)
print(c)

# Identity matrix - size/square matrix
d = np.eye(4)
print(d)

# Random matrix
randomMatrix = np.random.random((2,3)) 
print(randomMatrix)

# All inbuilt functions will generate matrices with float values unless mapped or specified

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.90284075 0.18544622 0.85348442]
 [0.40376043 0.87817593 0.97004446]]


### Reading and Updating elements

In [12]:
print(randomMatrix[:,1]) 
# will print the whole second column(i.e. index startes from zero) as all rows are selected(':')

[0.18544622 0.87817593]


In [13]:
# Updating particular elements
# Using slicing

print(randomMatrix)
randomMatrix[1, 1:] = 1 # Selects columns 2 and 3 of 2nd row and updates them
print(randomMatrix)

[[0.90284075 0.18544622 0.85348442]
 [0.40376043 0.87817593 0.97004446]]
[[0.90284075 0.18544622 0.85348442]
 [0.40376043 1.         1.        ]]


In [14]:
# Set some rows and columns with any values
z = np.zeros((3,3))
print(z)

z[1, :] = 5 # Assigns value 5 to 2nd row
z[:, -1] = 7 # Assigns value 7 to last column

print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 7.]
 [5. 5. 7.]
 [0. 0. 7.]]


### Datatypes in Numpy

In [15]:
print(z.dtype)

float64


In [20]:
# Changing datatype of z from float to int
z = np.zeros((3,3), dtype = np.int64)
print(z.dtype)
print(z)

# Data types in Numpy:

#bool             (boolean)
#int[8,16,32,64]  (integer)
#uint[8,16,32,64] (unsigned integer)
#float[8,16,32,64] (floating point number)
#complex[64,128]   (complex numbers)

int64
[[0 0 0]
 [0 0 0]
 [0 0 0]]


### Mathematical Operations

In [21]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

# Element Wise Addition
print(x+y)
print(np.add(x,y))

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [22]:
# Element Wise Subtraction
print(x-y)
print(np.subtract(x,y))
print(np.subtract(y,x))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[4 4]
 [4 4]]


In [24]:
# Element Wise Multiplication & Division
print(x*y)
print(np.multiply(x,y))

print('------------------------------------')

print(x/y)
print(np.divide(x,y)) # Always use np.divide() and not np.division()

print('------------------------------------')

# Element Wise Square root
print(x**(0.5))
print(np.sqrt(x))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]
------------------------------------
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
------------------------------------
[[1.         1.41421356]
 [1.73205081 2.        ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


### Matrix Multiplication / Dot Products

In [25]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [26]:
# Dot Product
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [48]:
# Multiplication of Vectors (linear arrays)
a = np.array([1,2,3,4])
b = np.array([1,2,3,4])
print(a.dot(b))
# Dot product returns a scalar

30


In [28]:
print(x)

# Sum of all elements
print(np.sum(x))

[[1 2]
 [3 4]]
10


In [32]:
# Can give additional and VERY USEFUL axis parameter
print(x)
print(np.sum(x, axis = 0)) # Will give sum along the columns

print('---------------------------')
print(np.sum(x, axis = 1)) # Will give sum along the rows

[[1 2]
 [3 4]]
[4 6]
---------------------------
[3 7]


### Stacking and Reshaping of Arrays

In [49]:
print(a)
b = a**2
print(b)

[1 2 3 4]
[ 1  4  9 16]


In [50]:
np.stack((a,b), axis = 1)
# This basically concatenates the two arrays according to the specified axis
# In this case (row wise) it will take the whole arrays and make it rows of the resultant array

array([[ 1,  1],
       [ 2,  4],
       [ 3,  9],
       [ 4, 16]])

In [51]:
# Column wise concatination/ stacking
a = np.stack((a,b), axis = 0)
a

array([[ 1,  2,  3,  4],
       [ 1,  4,  9, 16]])

In [52]:
print(a)
print(a.shape)

[[ 1  2  3  4]
 [ 1  4  9 16]]
(2, 4)


In [53]:
# Reshaping a Numpy array
a = a.reshape((4,2)) # Will reshape it into 4x2 matrix but while specifying (r,c)
print(a)             # rxc should beeqal to old(rxc)


[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]


In [56]:
a = a.reshape((8,1))
print(a)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 1]
 [ 4]
 [ 9]
 [16]]


In [57]:
#------------IMPORTANT-------------
# To convert it into a linear array
a = a.reshape((8,))
print(a)

[ 1  2  3  4  1  4  9 16]


In [58]:
#-----------IMPORTANRT--------------
# If we dont know either the number of rows or columns, Numpy can calculate that for us
a = a.reshape((4,-1)) # Give '-1' in place or R/C and it will automatically insert the right value
print(a)
print(a.shape)

[[ 1  2]
 [ 3  4]
 [ 1  4]
 [ 9 16]]
(4, 2)
