# NumPy Random Module
* rand: Random values in a given shape
* randn: Return a sample(or samples) from the "standard normal" distribution
* randint: Return random integers from low(inclusive) to high(exclusive)
* random: Return random floats in the half-open interval \[0.0, 1.0)
* choice: Generates a random sample from a given 1-D array
* Shuffle: shuffles the contents of a sequence

In [1]:
import numpy as np

In [9]:
a = np.arange(10) + 5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [10]:
# To shuffle the elements of array
np.random.shuffle(a)
print(a)

[ 9  5 13  6 14 12  7 11  8 10]


### Generating Random numbers

In [11]:
# Generate a mxn matrix of random floats in range [0,1)
a = np.random.rand(2,3) # No need to give size as tuple
print(a)

[[0.73243419 0.91606554 0.65565111]
 [0.01019956 0.58200298 0.36364682]]


In [12]:
# Generates a mxn matrix of random floats from standard normal distribution
a = np.random.randn(2,3)
print(a)

[[ 1.0275266  -0.51485389  0.02889368]
 [-0.30376467  0.52435418  0.14559567]]


In [13]:
# This returns n random integers from the given range [low, high)
a = np.random.randint(5,10,3)
print(a)

[9 5 8]


In [16]:
a = np.random.randint(2,12,(3,3))
print(a)

[[ 2 11  7]
 [10  9 10]
 [ 5  4  7]]


In [18]:
# Randomly picks an element from any array
element = np.random.choice([1,4,6,23,9,34]) # Can take only 1D arrays
print(element)

9


### Seeding in pseudo random number generators

In [ ]:
'''Seeding is imp as the random number generators use same number once initiated to 
generate all random arrays or matrices'''

'''By manually ensuring the seed for these generators you can generate the same random values
each and every time'''

In [2]:
# How to give seed value
np.random.seed(1)
element = np.random.choice([1,4,6,23,9,34]) # Can take only 1D arrays
print(element)

34
