# Statistical NumPy Functions
* min, max
* mean
* median
* average
* variance
* standard deviation

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4], [7,6,2,0]])
print(a)

# To get minimum element of an array
print(np.min(a))

[[1 2 3 4]
 [7 6 2 0]]
0


In [5]:
# To get minimum elements in each column
print(a)
print(np.min(a, axis = 0))

[[1 2 3 4]
 [7 6 2 0]]
[1 2 2 0]


In [6]:
# To get minimum elements in each row
print(a)
print(np.min(a, axis = 1))

[[1 2 3 4]
 [7 6 2 0]]
[1 0]


### Mean: Average of all the elements

In [7]:
b = np.array([1,2,3,4,5])

# Calculating mean by formula
n = sum(b/len(b))
print(n)

# Calculating mean directly
print(np.mean(b))

3.0
3.0


In [9]:
print(a)

# Mean along column
print(np.mean(a, axis=0))

# Mean along row
print(np.mean(a, axis=1))

[[1 2 3 4]
 [7 6 2 0]]
[4.  4.  2.5 2. ]
[2.5  3.75]


### Median: Middlemost value

In [10]:
c = np.array([1,5,4,2,0])
print(np.median(c))

2.0


In [12]:
# Mean: column and row wise
print(np.mean(a, axis = 0))
print(np.mean(a, axis = 1))

[4.  4.  2.5 2. ]
[2.5  3.75]


### Mean vs Average
* Mean is simply the sum of elements divided by total number of elements
* Average is the same but it is or can be weighted if we want it to be<br>
by weighted we mean that there is a weight assigned to each element which is multiplied
to its respective element when computing average and then divided by total number of elements
* Mean is simple and can never be weighted

In [13]:
# Mean
print(np.mean(c))

# Average: Simple
print(np.average(c))

# Average: Weighted
w = np.array([1,2,3,4,5])
print(np.average(c, weights=w))

2.4
2.4
2.066666666666667


### Standard Deviation
* This is the total deviation of all the values from the mean or average value
* Formula: sqrt(summation((x - mean)^2)/N)
* Variance = square of standard deviation
* We squared the difference of each  value and mean '(x-u)' because it eliminates the error of minus sign or of absolute value

In [14]:
# Standard Deviation by building our own formula
u = np.mean(c)
mystd = np.sqrt(np.mean(abs(c-u)**2))
print(mystd)

# Standard Deviation by inbuilt formula
std = np.std(c)
print(std)

# We will obtain the same value

1.854723699099141
1.854723699099141


In [15]:
# Variance:
print(std**2)
print(np.var(c))

3.440000000000001
3.4400000000000004
